version: '3.8'

services:
  express-app-for-test:
    container_name: express-app-for-test
    build: .
    ports:
      - "3001:3001"
    environment:
      - DOCKER_ENV=true
      - DB_HOST_DOCKER=express-app-test-db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
      - DB_PORT=3306
    depends_on:
      express-app-test-db:
        condition: service_healthy
    networks:
      - express-network  

  express-app-test-db:
    container_name: express-app-test-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - express-network 
    volumes:
      - mysql_data:/var/lib/mysql  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  express-network:
    driver: bridge  

volumes:
  mysql_data:  